### ISSUE TITLE
Add GH Action Cron Job to Update Daily

### ISSUE THREAD

**Issue by tuananh** [chainguard-dev/image-comparison#2]
github action to update the list daily maybe? that would be nice :)

**Comment by jspeed-meyers** [comment]
@tuananh, sorry for the slow response :(

We do this internally right now, but our plan is to keep this dataset (mostly) static and (mostly) unchanging since the website graph is not supposed to update (frequently). Though we did just update today :)

**Comment by jspeed-meyers** [comment]
Take two: Actually, I'm going to try to make this happen (likely with support from @jdolitsky). Here goes nothing!

Some specifications:

- It will pull data from 32 days ago to 2 days. (This allows a little time to debug in case something breaks.)
- Will be a GH action cron job.

Nice to have:
- Use some combo of wolfi, melange, and apko to accomplish.

**Comment by jspeed-meyers** [comment]
Okay, all the basics are here. I'll check in in 24 hours to see how the first official cron job goes. If something has caught on fire, then I'll call the fire department (myself and @jdolitsky) and we'll fix it :)

**Comment by jspeed-meyers** [comment]
Well, no fire, more like a false start. The new action created this error:
```
Warning: Python 3.10 was not found on your system...
Neither 'pyenv' nor 'asdf' could be found to install Python.
```
Let me put in a PR to try with the job with Python 3.10.

**Comment by jspeed-meyers** [comment]
@tuananh, @jdolitsky and I THINK it's working now. Closing the issue. Thank you for prodding us!
