### ISSUE TITLE
Implement gitsign in publishing step

### ISSUE THREAD

**Issue by jspeed-meyers** [chainguard-dev/image-comparison#26]

**Comment by jspeed-meyers** [comment]
@wlynch, is possible to add keyless signing via a GH action? 

I wanted to add it somewhere in here:

https://github.com/chainguard-dev/image-comparison/blob/main/.github/workflows/pull_data.yml

When I tried earlier, I got this error:

```
error: gpg failed to sign the data
```

Thank you for any help!!

**Comment by wlynch** [comment]
Yes! https://github.com/chainguard-dev/actions/tree/main/setup-gitsign
